resolver: lts-9.0

packages:
- '.'
- location:
   git: https://github.com/commercialhaskell/stack.git
   commit: 6eda315554dc780196275df9dec90a9fe57b8cf7
  extra-dep: true


extra-deps:
- hnix-0.3.4

flags: {}

extra-package-dbs: []
