resolver: lts-9.11

packages:
- '.'
- location:
   git: https://github.com/commercialhaskell/stack.git
   commit: aa5003a153504f54051e42a844a0c1c3d7f82163
  extra-dep: true

extra-deps:
- hnix-0.3.4
- bindings-uname-0.1
- Cabal-2.0.0.2
- cabal2nix-2.7
- hackage-db-2.0

flags: {}

nix:
  packages: [zlib,gmp,git,pcre,openssl,haskellPackages.happy]

extra-package-dbs: []
